const data = {
  products: [
    {
      _id: "1",
      name: "Sepatu Bagus",
      category: "Sepatu",
      image: "sepatuBagus.jpg",
      countInStock: 1,
      price: "120.000",
      brand: "Nike",
      description: "Good",
    },
    {
      _id: "2",
      name: "Sepatu Bekas",
      category: "Sepatu",
      image: "sepatuBekas.jpg",
      countInStock: 1,
      price: "30.000",
      brand: "Adidas",
      description: "Good",
    },
    {
      _id: "3",
      name: "Kacamata",
      category: "Lainnya",
      image: "kacamata.jpeg",
      countInStock: 1,
      price: "100.000",
      brand: "Calvin Klein",
      description: "Good",
    },
    {
      _id: "4",
      name: "Kaos",
      category: "Baju & Celana",
      image: "kaos.jpg",
      countInStock: 1,
      price: "120.000",
      brand: "Nike",
      description: "Good",
    },
    {
      _id: "5",
      name: "Sandal Gunung",
      category: "Sepatu",
      image: "sandalGunung.jpg",
      countInStock: 1,
      price: "133.000",
      brand: "Nike",
      description: "Good",
    },
    {
      _id: "6",
      name: "Baju Bagus",
      category: "Sepatu",
      image: "bajuBagus.jpg",
      countInStock: 1,
      price: "120.000",
      brand: "Nike",
      description: "Good",
    },
  ],
};

export default data;
